base: 'https://ddev-typo3.ddev.site/'
baseVariants: {  }
errorHandling:
  -
    errorCode: '404'
    errorHandler: Page
    errorContentSource: 't3://page?uid=5'
languages:
  -
    title: English
    enabled: true
    languageId: '0'
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    direction: ltr
    flag: en-us-gb
    websiteTitle: ''
  -
    title: Deutsch
    enabled: true
    languageId: '2'
    base: /de/
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ltr
    fallbackType: fallback
    fallbacks: '0'
    flag: de
    websiteTitle: 'TYPO3 Entwickler'
rootPageId: 1
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nDisallow: /typo3_src/\r\nDisallow: /content-examples/\r\nDisallow: /en/content-examples/\r\n# Keine Backups \r\nDisallow: *.tar.gz\r\nDisallow: *.sql\r\nDisallow: *.sql.gz\r\nAllow: /typo3/sysext/frontend/Resources/Public/*\r\n"
websiteTitle: 'TYPO3 Developer'
