#!/usr/bin/env bash

## Description: Run typo3 scheduler:run on every minute
## Usage: t3cron
## Example: "ddev t3cron"

while true
do
  sleep 60
  /var/www/html/public/typo3/sysext/core/bin/typo3 scheduler:run
  echo 't3cron run'
done
