version: '3.6'

services:
  web:
    environment:
      - TYPO3_CONTEXT=Development
      - PHP_IDE_CONFIG=serverName=${DDEV_SITENAME}.ddev.site
    volumes:
      # add php xdebug profile path
      - ./php-profiles/:/tmp/debug/:delegated
    # ports:
    #   - 8899:80